name: Deploy to Heroku

on:
  push:
    branches: ["main", "master"]  # Adjust to your default branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Heroku
        run: |
          git remote add heroku https://article-api-application-53ee1404371a.herokuapp.com/
          echo "machine api.heroku.com" > ~/.netrc
          echo "  login ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
          echo "  password ${HEROKU_API_KEY}" >> ~/.netrc
          echo "machine git.heroku.com" >> ~/.netrc
          echo "  login ${HEROKU_API_KEY}" >> ~/.netrc
          echo "  password ${HEROKU_API_KEY}" >> ~/.netrc

      - name: Push to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git push heroku master
